[package]
name = "milans_rust_logging"
version = "0.1.0"
edition = "2021"

[dependencies]
log4rs = "1.3.0"
once_cell = "1.19.0"

[features]
default=["log"]
log=[]
debug=[]
trace-log=[]
internal-config=[]
auto-config=[]
